apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: my-workspace
spec:
  organization: rosemaryagain
  secretsMountPath: "/tmp/secrets"
  module:
    source: "app.terraform.io/rosemaryagain/hello/random"
    version: "2.0.1"
  variables:
    - key: hello
      value: rosemary
      sensitive: false
      environmentVariable: false
    - key: secret_key
      sensitive: true
      environmentVariable: false
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true