apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workspaces.app.terraform.io
spec:
  group: app.terraform.io
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Workspace is the Schema for the workspaces API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkspaceSpec defines the desired state of Workspace
          properties:
            module:
              description: Module source and version to use
              properties:
                source:
                  type: string
                version:
                  type: string
              required:
              - source
              - version
              type: object
            variables:
              description: Variables as inputs to module
              items:
                properties:
                  key:
                    type: string
                  sensitive:
                    type: boolean
                  value:
                    type: string
                required:
                - key
                - sensitive
                - value
                type: object
              type: array
          required:
          - module
          type: object
        status:
          description: WorkspaceStatus defines the observed state of Workspace
          properties:
            configHash:
              description: Configuration hash
              type: string
            outputs:
              description: Outputs
              items:
                type: string
              type: array
            runID:
              description: Run ID
              type: string
            workspaceID:
              description: Workspace ID
              type: string
          required:
          - configHash
          - outputs
          - runID
          - workspaceID
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
