apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: example-workspace
spec:
  module:
    source: "app.terraform.io/rosemarycorp/hello/random"
    version: "1.0.0"
  variables:
    - key: hello
      value: rosemary
      sensitive: false